### ISSUE TITLE
Maybe update record to reflect that we now use ibm rather than bluemix

### ISSUE THREAD

**Issue by donovat** [ibm-cloud-docs/account#14]
On this page the crn example all have bluemix,which is now being replaced my ibm. So maybe the examples need to reflect this.The page in question is; https://cloud.ibm.com/docs/account?topic=account-crn

**Comment by KentHall2018** [comment]
Hi @donovat. Thanks for opening this issue. I'm looking into the details and will hopefully have an update for you soon.

**Comment by KentHall2018** [comment]
@donovat According to our guidance and specifications, the use of `bluemix` as the `cname` segment in the CRN is still the only valid option for production. I also confirmed the information with the engineers that own those specifications. They did say that there were discussions about changing it but ultimately opted to keep `bluemix`. 

Do you have examples of CRNs that are used that have `ibm` instead of `bluemix` in the CRN?

**Comment by donovat** [comment]
Hi @KentHall2018 - I have a support call open with the ibm cloud db2 team, having issues with a service after an instance migration. They came back to me with the following crn as my new crn. 
crn:v1:ibm:gb:dashdb-for-transactions:eu-gb:a/6ffa17fcf55f41cf9c082c34e772b17c:ea286ace-86c7-4d5b-8580-3fbfa46b1c66::

As you can see no bluemix in the line.

**Comment by KentHall2018** [comment]
@donovat I was just about to ask if the CRN with `ibm` was working, but the console updated it to have `bluemix`? And it's working?

**Comment by donovat** [comment]
I open the console via a "Go to UI" button from the ibm services console. So not sure if the use ibm or bluemix, but the rl has bluemix, and is now working. (it originally did not and the db2 team had to fix, so it could be this they fixed. 
So its hard to say. It could be that db2 support just gave me bad info.

**Comment by KentHall2018** [comment]
@donovat I'm glad it got fixed and that it's working. I'm going to consider this issue closed. thanks again for opening it.
