### ISSUE TITLE
Problems with deleting a resource group

### ISSUE THREAD

**Issue by Jiraiya106** [ibm-cloud-docs/account#16]
When removing infrastructure using terraform destoy. A resource group deletion error occurs. "message": "Resource Group with instance cannot be deleted". But by checking the content of the group using ibm cli I see that it is empty. By running the terraform destroy command 3-5 minutes after this error is displayed, it completes successfully.

**Comment by KentHall2018** [comment]
@Jiraiya106 I talked to one of the developers and they said that this could have happened because of a couple of reasons, but it's hard to tell without knowing the exact situation. 

Basically, in the CLI call, you’d need to specify --type all to get ALL the resources in that group

I’m not sure what instances were left that caused that 1st try to fail but after the 1st fail you should query with --type all to check for instances

Some services have dependencies where they’ll accept the delete but it's in progress. We're guessing that the progress completed which made your dependency gone, so the subsequent retry works.

So, if it fails, check with  --type all to see if there indeed are instances left.

I hope that this is helpful and thank you for opening this issue.
