### ISSUE TITLE
How do you create a Functional ID

### ISSUE THREAD

**Issue by mjdavisibm** [ibm-cloud-docs/account#6]
The page recommends using a functional ID to restrict what exactly what an api key can access, but I can not find any documentation on how to create one

**Comment by addison-martin1** [comment]
Hi @mjdavisibm, 

To create a functional ID, you'll have to create a new user in your user directory and invite them into IBM Cloud. A user directory stores all user information, and is managed by a program like Active Directory. If you federate your identity provider (IdP) with IBMid, then any user in your user directory could be invited to an IBM Cloud account. 

A functional ID is a non-human user in the user directory. So the first step is to create a new user in your user directory, for example, myFunctionalUser@mycompany.com. You can invite this functional user to the IBM Cloud account. This functional user is used instead of a real user so that things like Kubernetes clusters can be created with that user. This way, you don't have to worry about the user ever leaving the company since it is not tied to a real person.

Please let me know if you have any follow-up questions. I'll be sure to update our documentation to include this guidance.
